jisaacks/GitGutter

- README.md
GitGutter wasn't working until I installed this package. I had installed git with [homebrew](http://brew.sh/) on my Mac
> Suggest SublimeFixMacPath on OSX

- Main.sublime-menu
This PR changes the capitalization of the `Previous Change` and `Next Change` menu items to look more similar to the surrounding menu items. For reference, here is a screenshot of the current Goto menu:
> Fix capitalization of menu items

- git_gutter_handler.py
GitGutter did not work on my Win7/Cygwin, ST3 setup.  Explicitly specifying `no-index` to the diff subprocess (instead of relying on implicit detection) fixes the issue, and poses no risk to other systems.
My symptoms are the same as #191:
* Args to Popen: ['git', 'diff', '-U0', '--no-color', '--patience', 'c:\users\...\temp\tmpxxxxxx', 'c:\users\...\temp\tmpyyyyyy']
* Results of above subproc to stdout are an empty binary string: b''
* Running the command on the CLI (cmd, or bash) results in a good diff
I agree with @0m4r in #146 that the problem is in git, which fails to correctly identify when Windows paths are outside the repository (when using Cygwin), even though it does handles those Windows paths when `no-index` is used explicitly. Perhaps the issue is inside …
> Fix for ST3 not working with Cygwin git

- GitGutter.sublime-settings
- README.md
- git_gutter.py
- git_gutter_handler.py
I've added support for showing gutter marks in the minimap (#55), but it only works on ST3.
Unsure if you want to merge or not because of this, however it does safely disable in ST2.
Here's a screenshot showing ST3 and ST2 respectively.
Here's a non-retina screenshot showing a much bigger file. Makes it a lot easier to spot diffs.
> Add minimap support (ST3 only)

- git_gutter.py
example case: `r` is `(387, 387)` and `region` is `(387, 388)`
> fix protected_regions check

- view_collection.py
After a long sublime session I find my /tmp directory littered with temp files created by Git Gutter. It's worse on Windows where the %TEMP% directory is persistent. It would be helpful to be able to identify files left behind by GitGutter so they can be manually cleaned up.
Ideally Git Gutter would remove these files when they are not needed. I'll work on that next.
> Add an identifiable prefix to temp files

- README.md
Originally:
If `git` is not found but GitGutter...
Fixed:
If `git` is not found BY GitGutter...
> [fix] typo in "Git Path" section

- GitGutter.sublime-settings
- README.md
- git_gutter_handler.py
On Windows, git isn't always in PATH, requiring you to set git_binary for GitGutter to work correctly.  For users that sync settings across platforms, this allows git_binary to be (optionally) customized on a per-platform basis.
> Allowing git_binary to be customized on a per-platform basis.

- git_gutter_handler.py
After #242 there was missing `shutil` dependency in `git_gutter_handler.py`.
> Fix issue #294 with shutil errors.

- GitGutter.sublime-settings
Prevent GitGutter from overwriting bookmark icons.
> Add bookmarks to protected regions

- git_gutter.py
This checks whether the protect region is anywhere in the line and not only at the start of the line. Since the gutter icon is applied to the whole line, it should also checked in the whole line, whether a gutter icon has been added.
> Check the protected regions in the whole line.

- git_gutter.py
- git_gutter_change.py
- git_gutter_events.py
- git_gutter_handler.py
- git_gutter_popup.py
- git_gutter_settings.py
- view_collection.py
This is first step towards rewrite of the code to have less globals and more
passing of objects around.
Created GitGutterSettings class which is created in ViewCollection and passed
onto GitGutterHandler's created from there.
The goal is to remove the ViewCollection and pass settings directly from the
base *Command class. Currently settings object is still created in a couple of
places (ViewCollection, individual "WindowCommand"s and EventListener). In the
end it will be created only from the base TextCommand and EventListener.
> Add GitGutterSettings class that encapsulates settings (#230 related)

- git_gutter_popup.py
mdpopups converts spaces into non-breakable spaces on its own in version 1.11.0 https://github.com/facelessuser/sublime-markdown-popups/issues/14, so this conversion is not necessary if that version is used.
> Don't make spaces unbreakable with the new mdpopups

- git_gutter.py
- git_gutter_handler.py
Delete temporary files on destruction of GitGutterHandler class. Chosen to
remove them from destructor rather than from on_view_close event as it's more
reliable. During on_view_close event, the git command might still be running so
it might be too early to delete temporary files. This seems to work even when
closing Sublime with many files where git gutter has triggered.
Also:
- Create GitGutterHandler lazily, when any of the commands is run rather
than on creating the instance of the GitGutter text command itself. That
ensures that we only create temporary files when actually needed rather than
immediately for every view that is open in the editor.
- Disable GitGutter in all native input fields (for example search field shown
on pressing ctrl+f). All those views don't need GitGutter for …
> Make sure temporary files are deleted after view is closed (fixes #284)

- git_gutter_settings.py
During #315 I've introduced a small issue with handling
`git_binary_path_fallback`. The static
`GitGutterSettings.git_binary_path_fallback` was assigned but never read (we
read from `self._git_binary_path_fallback` instead which was always None). The
only issue that stemmed from it, was that we recalculated git path every time
the settings were changed (so not that big of a deal) rather than only once.
Fixed by using same property when both setting and getting it. Also made the
property instance-local as there is only one instance of Settings currently so
there is no need to use static properties. Same goes for
`git_binary_path_error_shown`.
(The code, as before, won't update git_binary_path when user changes the config
file but that is a separate issue.)
> Fixup git_binary_path_fallback handling

- git_gutter_popup.py
Fix #335 
I would merge this soon to fix the bug for GitGutter-Edge users. Since the Bug is only for Edge users it does not need a new release.
> Change the way the popup css files are loaded

- git_gutter_settings.py
It's important that all code shares the same instance of GitGutterSettings.
One reason that this is needed is when we trigger an error on not finding
a git binary. With multiple instances, all will check their own state
of _git_binary_path_error_shown property and we'll end up with multiple
message dialogs.
Fix by checking globals and avoiding creation of GitGutterSettings instance
if it already exists. This is needed as importing git_gutter_settings.py
always re-evaluates the code and that ended up creating new instances.
> Create only one instance of GitGutterSettings (fixes #334)

- git_gutter_events.py
- git_gutter_handler.py
- git_gutter_jump_to_changes.py
- git_gutter_show_diff.py
Hello guys, very much thanks for your incredible good work with GitGutter 1.4.0. 
A also made up my mind how to improve this plug-in a little bit and found two things I would like to discuss or already started to in the issues section.
Sorry for I was not yet able to distinguish the commits to make a pull request for each.
1. Create temp files only for views, whose content is stored in a git repository. (trivial minor improvement)
2. Run Git and diff only if necessary and avoid running it twice.
I think it's better to talk about real code, than generally discuss things. I know there are some concerns about the second probosal and I am sure it needs extensive testing before productive use, but I think it could generally help saving some CPU in the background.
The basic idea behind it is to …
> Some usage optimization

- git_gutter_compare.py
- git_gutter_handler.py
- git_gutter_settings.py
- git_gutter_show_diff.py
Change from "compare to" target being globally applied for all files to
being applied per git repo as only that makes sense.
> Make "compare to" functionality work per git directory (fixes #327)

- git_gutter_handler.py
Trying to invoke git always throws the following error to my
console:
OSError: [WinError 6] The handle is invalid
Populating stdin/stderr with subprocess.PIPE fixes the problem.  I
think this is the following Python bug:
https://bugs.python.org/issue3905
Note that some others have tripped across this issue, too.  See the
second comment by @flux242 in issue #146.
> Fix error invoking git which happens on all of my Windows systems.

- GitGutter.sublime-settings
- git_gutter_handler.py
- git_gutter_popup.py
- git_gutter_show_diff.py
The documentation of `show_markers_on_untracked_file` setting quite clearly says: "GitGutter shows icons for new files and ignored files." 
GitGutter 1.3.0 did behave exactly like documented.
> git diff is called only for files, which are not marked untracked or ignored.
GitGutter 1.4.0 shows '+' markers on each line for any file within a git repository even with `show_markers_on_untracked_file: false`.
> git diff is called first and then a check is performed, whether the file might be untracked or ignored.
This pull request intends to revert the behaviour to as it was on 1.3.0 to satisfy documentation.
`show_markers_on_untracked_file: false`
-> do not show any marker on ignored, untracked or new files.
`show_markers_on_untracked_file: true` (Default)
-> show '*' for untracked files
-> …
> Let user show/hide markers on new, ignored and untracked files

- Default (Linux).sublime-keymap
- Default (OSX).sublime-keymap
- Default (Windows).sublime-keymap
- Default.sublime-commands
- README.md
- git_gutter.py
- git_gutter_compare.py
- git_gutter_handler.py
- git_gutter_jump_to_changes.py
- git_gutter_popup.py
- git_gutter_show_diff.py
Hello guys,
I was always confuesed about the `Comparing against: ...` status messages. It always shows HEAD or a commit hash. I never saw the name of a branch selected to compare against. While investigating the performance issue #26 I found the answer and decided to create this pull request. Hope you'll find it as useful as I do.
`Comparing against branch` doesn't actually tell GitGutter to compare against the HEAD of the selected branch but only against the currently latest commit. This has two side effects. The branch name is not displayed in the status bar and if the branch forwards, GitGutter won't see that.
1. Save the whole `refs/heads/...` or `refs/tags/...` strings instead of commit numbers, if `Compare against branch` or `Compare against tag` was called.
2. Suggestion (1) …
> Enhancement for 'Comparing against' system

- git_gutter.py
- git_gutter_handler.py
The documentation about python's `subprocess` module makes some recommendations
about how to handle subprocess calls, which are applied by this commit.
> Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to
avoid deadlocks due to any of the other OS pipe buffers filling up and blocking
the child process.
So maybe we should use it.
>The child process is not killed if the timeout expires, so in order to cleanup
properly a well-behaved application should kill the child process and finish
communication.
Would be nice but is not supported by python 2.6 and therefore does not work
with SublimeText 2.
> The most common exception raised is OSError. This occurs, for example, when
trying to execute a non-existent file. Applications should prepare for OSError
exceptions.
Catch …
> Securing git execution.

- git_gutter_events.py
We need to use the view id to check the view is the active one in a group.
> Fix issue: GitGutter ignores on_modified() event in ST2, because view visibility check fails.

- Default (Linux).sublime-keymap
- Default (OSX).sublime-keymap
- Default (Windows).sublime-keymap
- Default.sublime-commands
- GitGutter.sublime-settings
- Main.sublime-menu
- README.md
- dependencies.json
- git_gutter.py
- git_gutter_compare.py
- git_gutter_handler.py
- git_gutter_jump_to_changes.py
- git_gutter_popup.py
- git_gutter_settings.py
- git_gutter_show_diff.py
I'd like to introduce the following changes to GitGutter. I packed several things into this PR as they all belong together, modify the same parts of code and would otherwise make too much work to merge correctly again as they base on each other.
The first commits are some kind of infrastructure changes to ease handling of git output and reduce some cross references of git_gutter modules. They mainly intend to reduce required lines of code. They are the base of the following functional changes and additions.
I was always confuesed about the Comparing against: ... status messages. It only shows HEAD or a certain commit hash instead of the name of a branch selected as compare target. 
Comparing against branch doesn't actually tell GitGutter to compare against the HEAD of the selected branch …
> Enhancements for the "Compare against ..."

- git_gutter_show_diff.py
If Sublime Text starts the very first time with GitGutter installed some
dependencies may not be satisfied yet, which results in an uncaught exception.
To avoid issues with the whole plugin loading process the depending functions
are disabled, if dependencies are not satisfied.
This commit disables the status bar text, if jinja2 library is missing.
> Fix: Avoid exception due to missing dependencies. (Issue #366)

- dependencies.json
The dependencies should be duplicated.
> The most-specific selectors will be used, and all other ignored. This
> means that some dependencies will be duplicated under a specific
> platform and under *.
https://github.com/wbond/package_control/blob/master/example-dependencies.json
> Readd dependencies to >=3080 entry

- Default.sublime-commands
- Main.sublime-menu
- git_gutter_settings.py
This commit introduces two ApplicationCommands:
1. `git_gutter_edit_settings` is a wrapper for the `edit_settings` command introduced with Sublime Text 3124 to show default and user settings side-by-side.
2. `git_gutter_open_file` is a wrapper for the `open_file` command in Sublime Text used to open settings files.
Both commands expand the variable ${package} to whatever the real local package name of GitGutter is and makes those commands work even if the package was renamed. By default it expands to 'GitGutter' but works with 'GitGutter-Edge', too. This fixes issue #220, even though @jisaacks doesn't want to support Edge anymore.
The second task of those wrapper commands is to make use of `edit_settings` without breaking backward compatibility for older Sublime Text builts.
The three …
> Fix Issue #220 and add Side-By-Side settings support

- git_gutter_handler.py
- modules/path.py
This is a fix for the issue of os.path.realpath() not to resolve symlinks on
Windows as it is an alias to abspath() only.
see: http://bugs.python.org/issue9949
As git_gutter_handler.py and the GitGutterHandler class grows too much,
the related functions for path handling are moved to a seperate module.
With respect to future plans for a modularized plugin structure, the
path functions are put into the folder 'modules'.
This is something maybe worth discussing as modularization in sub directories may have some advantages from my current point of view.
Several packages split their code to small modules contained in subdirectories to not pollute the globals of ST3. This enables export of only the API objects. As a result ST3 would show only a main module upon startup. This would also fix the …
> Fix: Resolve symlinks on Windows machines correctly (Issue #373)

- git_gutter_popup.py
- gitgutter_popup.css
This just replaces `{{wrapper_class}}` by the actual class, but keeps backward compat.
> Improve the css readability by directly writing the class

- release_messages/src/messages/1.5.0.txt
I generated the changelog based on V1.4.0 with GitSavvy and did some modifications to keep only the commit messages, which seem useful.
The order is defined by the commit dates. Hope this is ok.
Do we want to create a `1.5.0-rc.1` tag? Should it include changelogs and annotation or not?
> Add release notes for V1.5.0

- .gitignore
- git_gutter.py
- git_gutter_compare.py
- git_gutter_events.py
- git_gutter_handler.py
- git_gutter_jump_to_changes.py
- git_gutter_popup.py
- git_gutter_settings.py
- git_gutter_show_diff.py
- modules/path.py
- modules/promise.py
I checked and fixed some linter errors which I would like to include into the next release. Can you check for any regressions, please?
1. As suggested by google the imports are grouped into
a) system imports
b) global imports (ST API)
c) package imports
where possible and sorted by name.
2. ImportError is no longer catched from local relative imports as python 2 raises a ValueError only, if relative import fails. ImportError might be something worse, we want to see on ST3.
3. Generally changed all system- & global imports not to import functions or objects where possible. Use simple import <library> instead.
Added/fixed some docstrings to comply with pydocstyle and pylint.
Pylint suggested some methods to change to normal functions as they don't access any attribute. So I followed them. …
> Do some final code cleaning before release.

- release_messages/src/messages/1.5.0.txt
I added a suggestion for an anncouncement of the new pre-release strategy to the release-message
source file as suggested by FichteFoll.
Furthermore the 'Changes since ...' is replaced by the version number, so if several messages are merged, a list of versions and the changes can be displayed to the user.  Hope this is a good idea?
> Other: Add announcement for pre-releases to release-message source.

- git_gutter_handler.py
With introducing `git archive` command it was considered save to remove the `eol` mangling as correct translations should happen by this command.
This seems not to apply sometimes.
Reintroduce `eol` mangling for the files read from repository.
As the temporary view file is created from text, it should be written to disk with `\n` and thus shouldn't need mangling.
> Fix: Files are randomly marked as modified (Issue #381)

- git_gutter_compare.py
Git output can contain `\r` symbols as part of commit message. They shouldn't be treated as separators for refs results, so use only `\n` instead.
> Fix Compare Against when there are line breaks in git output

- git_gutter_show_diff.py
While binding untracked or ignored files, new gitgutter regions would
stop being added after the loop scanning the file detected any protected
region. In effect, this means that gitgutter would only display marks on
lines before the first protected region in untracked/ignored files.
> Fix bug in protected region handling for ignored/untracked files

- modules/path.py
Commit 57264b2 (#374) introduced `nt._getfinalpathname()`, which is importable
on Windows XP but throws `NotImplementedError` when called.
> Fix compatibility with ST3 on Windows XP

- release_messages/src/messages/1.6.0.txt
The only real issue reported this week was fixed, so I guess we are save to release 1.6.0
This PR includes the source file for the release message with all changes since 1.6.0-rc.1
I leave it up to @jisaacks to cut the release.
> 1.6.0 release

- .github/ISSUE_TEMPLATE.md
- Default.sublime-commands
- Main.sublime-menu
- README.md
- modules/__init__.py
- modules/support.py
Many issues contain only vague descriptions without required information
about the environment. This makes debugging hard.
Therefore this commit adds two things to solve this problem.
1. An ISSUE_TEMPLATE should help people to make up their minds about what might be
needed to successfully debug an issue.
2. A support module is added, which automatically collects some environment
variables and module versions, which might be interesting for developers.
Credits
-------
This commit is inspired by the support modules from
'BreaketHighlighter' by @facelessuser.
> Feature: Add support information module and ISSUE_TEMPLATE.

- GitGutter.sublime-settings
- README.md
- gitgutter_popup.css
- modules/popup.py
- modules/popup/__init__.py
- modules/popup/commands.py
- modules/popup/differ.py
- modules/popup/factory.py
I did a little work on diff popup module to hopefully enhance user experience with it.
1. Prepare to keep compatible with upcoming _mdpopups 2.0.0_
2. Add support to display wrapped content/diff (requires _mdpopups 2.0.0_)
3. Remove jinja2 template handling of CSS files as it is done by _mdpopups_ already
4. Optical enhancements of the popup itself
a) fix border width
b) adapt colors to color scheme
c) improve visibility on light color schemes
d) add some spacing around the navigation buttons
e) navigation buttons try to use fonts which are known to render the symbols well
f) use background colors to highlight diffs and distinguish replacements/inserts/deletions 
5. Avoid flickering if highlighting diff is enabled/disabled
6. Use the algorithm of difflib.Differ to create the highlighted …
> Diff Popup

- GitGutter.sublime-settings
- README.md
- modules/handler.py
- modules/settings.py
Issue #422 proposes the usage of `git diff --histogram` to determine file modifications.
This commit therefore replaces the "patience" setting by a more general "diff_algorithm". This key can be set to ("default", "minimal", "patience", "histogram") to select the desired diff algorithm. The setting is internally translated to the command line argument to ensure only valid arguments are passed to git.
> Enhancement: Add support for git diff --histogram algorithm (Issue #422)

- Default (Linux).sublime-keymap
- Default (OSX).sublime-keymap
- Default (Windows).sublime-keymap
- Default.sublime-commands
- README.md
- modules/__init__.py
- modules/commands.py
- modules/popup/factory.py
- modules/revert.py
With GitGutter's diff popup a user can revert a changed hunk to the state of the compared commit.
This commit moves the code to perform the revert operation into a dedicated module and adds it to the internal command chain:
1. Add the revert.py with the implementation moved from popup.factory module
2. Add "revert_change" to command map in the main GitGutterCommand class.
provides: `view.run_command("git_gutter", {"action": "revert_change"}`
3. Add TextCommand "git_gutter_revert_change" meant for external use.
provides: `view.run_command("git_gutter_revert_change"}`
4. Add an entry to the Default.sublime-commands
5. Add Ctrl+Shift+Alt+Z key binding.
6. Add a short note to the README.
NOTE: The revert operation does not work with multiple cursors at the moment.
---
Resolves #440
> Enhancement: Add command with keybinding to revert changes

- GitGutter.sublime-settings
- README.md
- modules/compare.py
Closes: #371
This PR changes the "Compare against Origin" function to store `<branch_name>@{upstream}` as compare target instead of `origin/<branch_name>` which might not have been useful in all use cases.
This modification enables a user to compare against the upstream revision of each currently checked out branch.
The command name an the title are not modified for backward compatibility reasons.
If the local branch doesn't have a tracked remote branch, each file is displayed as `inserted`.
> Fix: Compare against Origin (Issue #371)

- README.md
- modules/goto.py
This commit adds the arguments
- count  - number of iterations to find destination hunk
- wrap   - enable/disable wrapping at document boundaries
to the text commands:
- git_gutter_prev_change
- git_gutter_next_change
This change improves support for NeoVintageous package, but adds no new commands/functions to be executed directly.
> Enhancement: Add count and wrap arguments to goto commands. (Issue #458)

- modules/handler.py
The regex pattern used to parse the first line of the `git status -s -b` result accepted only word characters for branch names or `-`.
To resolve the issue and possibly others, each branch name can now consist of any none whitespace character.
The regex got quite complex. Anybody has better ideas to solve the issue?
> Fix: Branch name with dot is truncated on status bar (Issue #468)

- GitGutter.sublime-settings
A big update is coming to SublimeLinter, in which wake the default key has been changed.
See:
https://github.com/SublimeLinter/SublimeLinter3/pull/665
Old keys:
```
"sublimelinter-warning-gutter-marks",
"sublimelinter-error-gutter-marks",
```
Those old keys may still remain in there for a while after the rollout.
We are going to open another PR at a point in the future to remove those old keys.
> Added new SublimeLinter protected regions key

- GitGutter.sublime-settings
- Preferences.sublime-settings-hints
- modules/handler.py
The primary reason to add custom environment variables support is git adding some useful variables like GIT_OPTIONAL_LOCKS which can/will be used to optimize git runtime behavior without causing older versions to fail due to unsupported command line arguments.
In some cases being able to add/manipulate the environment might help fixing some edge cases.
> Enhancement: Add support for custom environment variables

- modules/handler.py
* add "-c color.status=never" option to `git status`, definitively disabling color output
{{branch}} is mis-parsed if `git status` output is colored (eg, when `git` is configured
with "config.status=always"). Using the "-c color.status=never" option overrides any user
configuration, displaying `git status` as uncolored in all cases and fixing the issue.
Notably, option ordering is important in this instance. The "-c ..." option is a `git`
base option, not a `git status` subcommand option. So, as done here, it must be inserted
before the "status" subcommand.
ref: Issue #474
> Fix: mangled {{branch}} text when `git status` output is colored (Issue #474)

- GitGutter.sublime-settings
- Preferences.sublime-settings-hints
- README.md
- modules/events.py
This PR adds support to ignore the hover event if a line is occupied by a certain region. The diff popup is not displayed by hovering such lines, but still can be opened by key binding or command pallet.
This enhancement is meant to improve compatibility with other packages.
> Enhancement: Add protected regions for diff popup (Issue #476)

- modules/handler.py
- modules/tempfile.py
Fixes issue #483
Introduces the `TempFile` class to handle access to temporary files and to ensure file deletion.
A look into python's tempfile module revealed a possible issue with temporary files not being removed on unix/linux/mac if `os.unlink()` is called within the `__del__()` method of an object. The `os` module might no longer exist at the point of time the `__del__()` is called especially upon application shutdown.
To ensure the files to be deleted, it is required to cache the `os.unlink()` function within the `TempFile` class and call the cached one within `__del__()`.
I don't have a Linux by hand at the time, so I'd ask for someone to test the new class on Linux and MacOS for a while to check whether file deletion works more reliable now.
The goal is not to keep any temporary …
> Enhancement: Place all temporary files into a dedicated sub directory.

- README.md
The actual default is `default`, so the readme shouldn't claim it's `patience`. It's already documented in the description table, so there's no need to mention it twice.
Also fixed a typo.
> Fix README documentation for `diff_algorithm`

- GitGutter.sublime-settings
Added protection for the gutter of [EasyClangComplete](https://packagecontrol.io/packages/EasyClangComplete) by default.
> Make EasyClangComplete regions protected by default

- modules/handler.py
GitGutter simply doesn't work when any external diff tool is in use.
This PR makes sure that GitGutter operations take place with the external diff tool disabled.
> Don't use extenral diff tool when performing diff
